import yfinance as yf
import pandas as pd
import pandas_ta as ta
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class MarketDataFetcher:
    def __init__(self):
        """
        Initializes the data fetcher. 
        yfinance doesn't require API keys for basic OHLCV data.
        """
        pass

    def fetch_historical_data(self, ticker: str, period: str = "1y", interval: str = "1d") -> pd.DataFrame:
        """
        Fetches historical OHLCV data for a given ticker.
        Note for Indian stocks: append '.NS' for NSE (e.g., 'TATAMOTORS.NS') or '.BO' for BSE.
        """
        logger.info(f"Fetching {period} of {interval} data for {ticker}...")
        
        try:
            stock = yf.Ticker(ticker)
            df = stock.history(period=period, interval=interval)
            
            if df.empty:
                logger.warning(f"No data returned for {ticker}.")
                return pd.DataFrame()
                
            # Clean up the dataframe
            df.reset_index(inplace=True)
            # Ensure date column is standard
            if 'Date' in df.columns:
                df.rename(columns={'Date': 'timestamp'}, inplace=True)
            elif 'Datetime' in df.columns:
                df.rename(columns={'Datetime': 'timestamp'}, inplace=True)
                
            df.columns = [col.lower() for col in df.columns] # lowercase columns: open, high, low, close, volume
            
            logger.info(f"Successfully fetched {len(df)} rows for {ticker}.")
            return df
            
        except Exception as e:
            logger.error(f"Error fetching data for {ticker}: {e}")
            return pd.DataFrame()

    def enrich_with_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Applies technical indicators using pandas-ta.
        """
        if df.empty:
            return df
            
        logger.info("Calculating technical indicators...")
        
        # Trend Indicators
        df.ta.ema(length=20, append=True)
        df.ta.sma(length=50, append=True)
        df.ta.sma(length=200, append=True)
        
        # Momentum Indicators
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        
        # Volatility (Average True Range)
        df.ta.atr(length=14, append=True)
        
        # Drop NaN values generated by rolling windows (e.g., first 200 days for SMA200)
        df.dropna(inplace=True)
        df.reset_index(drop=True, inplace=True)
        
        return df
        
    def get_latest_features(self, df: pd.DataFrame) -> dict:
        """
        Extracts the most recent row of data as a dictionary to feed the LLM agents.
        """
        if df.empty:
            return {}
        
        latest = df.iloc[-1].to_dict()
        # Convert timestamps to string for JSON serialization later
        latest['timestamp'] = str(latest['timestamp'])
        return latest

if __name__ == "__main__":
    # Quick test execution
    fetcher = MarketDataFetcher()
    # Using Tata Motors on NSE as an example
    df = fetcher.fetch_historical_data(ticker="TATAMOTORS.NS", period="1y", interval="1d")
    
    if not df.empty:
        enriched_df = fetcher.enrich_with_indicators(df)
        print("\nLatest Technical Snapshot:")
        latest_data = fetcher.get_latest_features(enriched_df)
        for k, v in latest_data.items():
            print(f"{k}: {v}")